
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    implementation_imports: false
    prefer_typing_uninitialized_variables: false
    library_private_types_in_public_api: false
    file_names: false
