name: cloudwalkone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #weather
  geolocator: ^11.0.0
  parallax_rain: ^1.1.1
  #utils
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  result_dart: ^1.1.0
  conversion_units: ^0.1.8
  #layout  
  flutter_screenutil: ^5.9.0
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  awesome_dialog: ^3.1.0

 #packages
  package_architecture: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_architecture.git
  package_database: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_database.git
  package_api: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_api.git
  package_module: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_module.git
  package_uikit:
    git:
      url: https://github.com/NandoPimenta/flutter_package_uikit.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_launcher_icons: 
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true



flutter:


  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/lottie/
 